# Generated by Django 2.2.9 on 2020-12-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('cidade', models.CharField(max_length=30, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Cliente',
            },
        ),
    ]
